# Bifrosts are counted as 0 - 4 AS A BOT.
# Use 0 - 4 below Please!
characters = [
    {
        "index": 0,
        "class": "sorceress",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1, # Check screenshots/Mokomoko_bifrost_start.png for starting location
    },
    {
        "index": 1,
        "class": "sorceress",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1,
    },
    {
        "index": 2,
        "class": "gunslinger",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1,
    },
    {
        "index": 3,
        "class": "deathblade",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": False,
        "rapport": False,
        "mokomokoBifrost": 1,
    },
    {
        "index": 4,
        "class": "bard",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1,
    },
    {
        "index": 5,
        "class": "glaivier",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1,
    },
    {
        "index": 6,
        "class": "gunslinger",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "slayer",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": False,
        "leapstones": True,
        "guildDonation": True,
        "rapport": False,
        "mokomokoBifrost": 1
    },
    {
        "index": 8,
        "class": "glaivier",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 9,
        "class": "berserker",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": True,
        "leapstones": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 10,
        "class": "artist",
        "ilvl-endless": 1520,
        "ilvl-aor": 1520,
        "lopang": True,
        "guildDonation": False,
        "rapport": False,
    },
    {
        "index": 11,
        "class": "sorceress",
        "ilvl-endless": 1490,
        "ilvl-aor": 1490,
        "lopang": True,
        "guildDonation": False,
        "rapport": False,
    },
]
