characters = [
    {
        "index": 0,
        "class": "sorceress",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },  
    {
        "index": 1,
        "class": "sorceress",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 2,
        "class": "gunslinger",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 3,
        "class": "deathblade",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 4,
        "class": "bard",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 5,
        "class": "glaiver",
        "ilvl-endless": 1560,
        "ilvl-aor": 1560,
        "lopang": False,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 6,
        "class": "gunslinger",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "glaivier",
        "ilvl-endless": 1540,
        "ilvl-aor": 1540,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 7,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
    {
        "index": 8,
        "class": "sorceress",
        "ilvl-endless": 1370,
        "ilvl-aor": 1370,
        "lopang": True,
        "guildDonation": True,
        "rapport": False,
    },
]
